Authorization
projectx-mobile/Mobile-App pull request #8
Opened 2022-09-10 11:58 UTC by Neveels

2022-09-12 07:48 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/controller/UserAccountController.java
> +        String link = "http://localhost:8000/email/confirm?token=" + token;
move to property file or smth like that

2022-09-12 07:51 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/controller/UserAccountController.java
> +                emailSender.buildEmail(email.getEmail(), link));
call this method inside service (the parameters will be just email and link)

2022-09-12 07:53 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/controller/request/EmailRequest.java
> +        this.email = email;
use lombok

2022-09-12 07:53 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/entity/ConfirmationToken.java
> +        this.confirmedAt = confirmedAt;
use lombok

2022-09-12 07:54 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/entity/User.java
> +//        this.password = password;
what is this comment for?

2022-09-12 08:07 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/service/imp/EmailServiceImp.java
> +                "</div></div>";
move to file, don't store such things in separate files

2022-09-12 08:08 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/google/GoogleController.java
> +@RequestMapping()
why did u add it?

2022-09-12 08:08 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/google/GoogleController.java
> +@CrossOrigin()
may u remove brackets?

2022-09-12 08:09 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/registration/controller/RegistrationController.java
> +@RequestMapping("/api/registration")
the same Q: why do u use this annotation ?

2022-09-12 08:11 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/registration/service/imp/RegistrationServiceImp.java
> +    public ResponseEntity<?> register(RegistrationRequest request) {
correct return value

2022-09-12 08:11 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/security_config/PasswordEncoder.java
> +import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
add empty line after

2022-09-12 08:12 UTC, VolgaDaniluk commented on authorization/src/test/java/com/jungeeks/controllers/ApplicationTests.java
> +}
what is it?)))))

2022-09-12 08:18 UTC, VolgaDaniluk requested changes
- add **private** to embedded values
- the messages of exteptions must start with a capital letter
- add empty lines where the need

2022-09-12 08:23 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/service/imp/EmailServiceImp.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(EmailServiceImp.class);
private static final

2022-09-12 08:25 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/registration/service/imp/RegistrationServiceImp.java
> +        if (!userRepository.findByEmail(request.getEmail()).isEmpty()) {
findByEmail return Optional. It's better way to call method isPresent instead of isEmpty

2022-09-12 08:26 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/service/imp/ConfirmationTokenServiceImp.java
> +    @Autowired
why do u do it into field?

2022-09-12 08:30 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/google/GoogleController.java
> +}
this controller = endpoint "/". Is it correct?

2022-09-12 08:32 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/security_config/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
WebSecurityConfigurerAdapter is depricated

2022-09-12 08:35 UTC, VolgaDaniluk requested changes
- change structure of the module
- remove unused dependensied and imports
- ResponseEntitu must be parameterized

2022-10-04 11:18 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/service/imp/ConfirmationTokenServiceImp.java
> +                token, LocalDateTime.now());
время лучше принимать в качестве параметра

2022-10-04 11:18 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/email/service/imp/EmailServiceImp.java
> +            helper.setFrom("FastEmaaiil@yandex.ru");
вынести почту в property

2022-10-04 11:18 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/firebase/FirebaseConfig.java
> +        }
использовать try-with-resources с inputstream

2022-10-04 11:18 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/firebase/FirebaseConfig.java
> +            assert inputStream != null;
не самая лучшая практика 
поменять на блок if

2022-10-17 18:41 UTC, anle751 commented
Complete auth

2022-10-19 10:01 UTC, VolgaDaniluk approved these changes
убрать закомментированный код
объяснить назначение HTML файла 
внести правки и можно сливать ветки

2022-10-19 10:01 UTC, VolgaDaniluk commented on accounts/build.gradle
> +//    testImplementation(platform('org.junit:junit-bom:5.9.1'))
remove commented tines

2022-10-19 10:01 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/controller/ClientRegistrationController.java
> +        return ResponseEntity.ok("OK");
зачем передавать "ОК" в ответе?

2022-10-19 10:01 UTC, VolgaDaniluk commented on authorization/src/main/java/com/jungeeks/entity/SecurityProperties.java
> +    boolean allowCredentials;
дефолтный модификатор?

2022-10-19 10:01 UTC, VolgaDaniluk commented on authorization/src/test/java/com/jungeeks/service/impl/UserServiceImplTest.java
> +        Mockito.when(userRepository.findByFirebaseId(any())).thenReturn(Optional.ofNullable(user));
сделать статический импорт

2022-10-19 10:01 UTC, VolgaDaniluk commented on authorization/src/test/java/com/jungeeks/service/impl/EmailServiceImplTest.java
> +        Mockito.when(checksumService.getChecksum(any(), any())).thenReturn(CHECK_SUM);
статический импорт (на все методы Mockito)

2022-10-24 16:43 UTC, merged